# Generated by Django 2.1.1 on 2018-09-26 03:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(default=0, max_length=11, validators=[django.core.validators.MinLengthValidator(11)]),
            preserve_default=False,
        ),
    ]
