# Generated by Django 2.1.1 on 2018-09-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.CharField(default='Não informado', max_length=100),
        ),
    ]
